### ISSUE TITLE
Source code available?

### ISSUE THREAD

**Issue by JeffBusch** [Sterophonick/mirror-meteo-avi2gba#1]
Hello,

Do you know if the source for Meteo was ever released? I was hoping to add functionality to the ROM like adding a splash screen.

Thanks

**Comment by Sterophonick** [comment]
To my knowledge, the source was never leaked or released, unfortunately.

**Comment by JeffBusch** [comment]
Ah, I kind of figured because I couldn't find much info about it.

Are there any alternatives, or a way to implement something similar into a homebrew game? Mostly looking to have the same video playback as Meteo with just a tiny bit of customization.

**Comment by Sterophonick** [comment]
None that I could find available.
